/* eslint-disable react/jsx-key */
import Head from "next/head";
import About from "../components/About/About";
import Navigation from "../components/AeroHome/Navigation/Navigation";
import Footer from "../components/Footer/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>About ZeddPay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <About />
      <Footer />
    </div>
  );
}
